package com.learn.seckill.dao;

import com.learn.seckill.entity.SeckillGoodsEntity;

public interface SeckillGoodsEntityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    int insert(SeckillGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    int insertSelective(SeckillGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    SeckillGoodsEntity selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SeckillGoodsEntity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table seckill_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SeckillGoodsEntity record);

    int reduceStock(SeckillGoodsEntity seckillGoodsEntity);
}