spring:
  datasource:
    username: root
    password: root
    #公司虚拟机
    url: jdbc:mysql://192.168.250.130:3306/seckill?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=true&autoReconnect=true&nullCatalogMeansCurrent=true&useAffectedRows=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 10
      minimum-idle: 10
      idle-timeout: 18000
      connection-timeout: 30000
      max-lifetime: 180000
      connection-test-query: SELECT 1
      auto-commit: true
  #集成redis
  redis:
    database: 0
    #公司虚拟机
    host: 192.168.250.130
    password:
    port: 6379
    timeout: 1000
    jedis:
      pool:
        max-active: 1000
        max-idle: 0
        max-wait: -1
        min-idle: 10
  thymeleaf:
    #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
    mode: HTML
    #编码 可不用配置
    encoding: UTF-8
    #开发配置为false,避免修改模板还要重启服务器
    cache: false
    #配置模板路径，默认是templates，可以不用配置
    prefix: classpath:/templates/

  swagger:
    learn:
      base-package: com.learn.seckill.controller
      description: seckill system
      contact-email:
      title: seckill
      enable: true
      version: 2.1
#资源静态化static
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      compressed: true
      html-application-cache: true
    static-locations: classpath:/static/
#自定义图片
  mvc:
    favicon:
      enabled: false
  #rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      simple: 
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
        auto-startup: true
        default-requeue-rejected: true
    template: 
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 10000
        multiplier: 1.0
#mybatis
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.learn.seckill.entity

#showSql
logging:
  level:
    com:
      learn:
        seckill:
          dao: debug