CREATE TABLE `test` (
	`id` INT (10) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '自增主键',
	`name` VARCHAR (255) DEFAULT NULL COMMENT '姓名',
	`age` INT (4) DEFAULT NULL COMMENT '年龄',
	PRIMARY KEY (`id`)
) ENGINE = INNODB AUTO_INCREMENT = 1 DEFAULT CHARSET = utf8mb4 COMMIT '测试';