package com.learn.seckill.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SeckillGoodsEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.good_code
     *
     * @mbg.generated
     */
    private String goodCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.seckill_price
     *
     * @mbg.generated
     */
    private BigDecimal seckillPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.stock_count
     *
     * @mbg.generated
     */
    private Integer stockCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.start_date
     *
     * @mbg.generated
     */
    private Date startDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column seckill_goods.end_date
     *
     * @mbg.generated
     */
    private Date endDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.id
     *
     * @return the value of seckill_goods.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.id
     *
     * @param id the value for seckill_goods.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.good_code
     *
     * @return the value of seckill_goods.good_code
     *
     * @mbg.generated
     */
    public String getGoodCode() {
        return goodCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.good_code
     *
     * @param goodCode the value for seckill_goods.good_code
     *
     * @mbg.generated
     */
    public void setGoodCode(String goodCode) {
        this.goodCode = goodCode == null ? null : goodCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.seckill_price
     *
     * @return the value of seckill_goods.seckill_price
     *
     * @mbg.generated
     */
    public BigDecimal getSeckillPrice() {
        return seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.seckill_price
     *
     * @param seckillPrice the value for seckill_goods.seckill_price
     *
     * @mbg.generated
     */
    public void setSeckillPrice(BigDecimal seckillPrice) {
        this.seckillPrice = seckillPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.stock_count
     *
     * @return the value of seckill_goods.stock_count
     *
     * @mbg.generated
     */
    public Integer getStockCount() {
        return stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.stock_count
     *
     * @param stockCount the value for seckill_goods.stock_count
     *
     * @mbg.generated
     */
    public void setStockCount(Integer stockCount) {
        this.stockCount = stockCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.start_date
     *
     * @return the value of seckill_goods.start_date
     *
     * @mbg.generated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.start_date
     *
     * @param startDate the value for seckill_goods.start_date
     *
     * @mbg.generated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column seckill_goods.end_date
     *
     * @return the value of seckill_goods.end_date
     *
     * @mbg.generated
     */
    public Date getEndDate() {
        return endDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column seckill_goods.end_date
     *
     * @param endDate the value for seckill_goods.end_date
     *
     * @mbg.generated
     */
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
}